### ISSUE TITLE
With 1.0.0-M4 `.cancel` on stream with inner queue never returns

### ISSUE THREAD

**Issue by seigert** [functional-streams-for-scala/fs2#1236] opened 2018-08-24 09:06 UTC
Not sure if this is issue with `fs2` or `cats-effect` itself, but following code:
```scala
object FiberCancelTest extends IOApp {
  def run(args: List[String]): IO[ExitCode] =
    async
      .synchronousQueue[IO, Int]
      .flatMap { q =>
        Stream(
          Stream
            .unfold(0)(i => (i + 1, i + 1).some)
            .flatMap { i =>
              Stream.sleep_(1.second) ++ Stream.emit(i)
            }
            .to(q.enqueue),
          q.dequeue.to(Sink.showLinesStdOut)
        ).parJoin(2).compile.drain.start.flatMap { f =>
          IO.sleep(5.seconds) *>
            IO(println("Canceling...")) *>
            f.cancel *>
            IO(println("Done."))
        }
      }
      .as(ExitCode.Success)
}
```
will perform as expected with `1.0.0-M3`: print four numbers, then `Canceling..`, then `Done`, then exit with code 0.

With `1.0.0-M4` app will print four numbers, then `Canceling`, then print fifth number and hang forever till killed with `SIGINT`.

If we remove `synchronousQueue` usage and will print number directly, everything will cancel just fine. But because queue constructor requires `Concurrent[F]` I think it should support cancellation.

**Comment by mpilquist** [comment] 2018-08-24 15:26
@pchlupacek `IO` has cancellation boundaries between binds now: https://github.com/typelevel/cats-effect/pull/311

It's true that there's no forceful Thread.interrupt though.

**Comment by pchlupacek** [comment] 2018-08-24 15:40
Yeah, thats my understanding too. However its just unclear how this really works together with Stream , i.e. would that really work with our interruption schematics. I remember trying to cancel Stream.constant did not work at all. Perhaps we could benefit with tests covering what types of stream will get cancelled and what not, including the finalisers etc.

**Comment by djspiewak** [comment] 2018-08-24 18:00
Interrupting `Stream.constant` has always been tricky (all the way back to 0.5 if memory serves). The standard solution here has been to represent `Stream.constant` explicitly using binds rather than append when you need interruption.

**Comment by mpilquist** [comment] 2018-08-25 13:50
I made some progress on this. Simple streams cancel fine, including `Stream.constant`. The issue is that lots of internal combinators use `F.start` and don't treat the started fiber as a resource. So when they are canceled, the fiber is left running. I think we generally want to replace internal usage of `F.start` with this combinator:

```scala
def supervise[F[_]: Concurrent, A, B](fa: F[A])(use: Fiber[F, A] => F[B]): F[B] =
  fa.start.bracket(use)(_.cancel)
```

Thoughts?

**Comment by SystemFw** [comment] 2018-08-25 13:55
I have been thinking for a while about a combinator that is similar in spirit:

```scala
def spawn(s: Stream[F, A]): Stream[F, Nothing] = Stream.never.concurrently(s)
```

(obviously can be implemented more lightly than concurrently).
`supervise` also looks good sematics wise, but it might (maybe) be a bit ugly for the same reason `F.bracket` without `Resource` is (nesting). Maybe we absolutely need to remain at the `F` level though? (I need to have another look at the offending code)

**Comment by mpilquist** [comment] 2018-08-25 14:02
`spawn` looks good.

> supervise also looks good sematics wise, but it might (maybe) be a bit ugly for the same reason F.bracket without Resource is (nesting)

You're absolutely right. I tried using `supervise` and it just doesn't fit. We need the fiber cleanup registered as a stream level resource. So now I'm thinking something like this:

```scala
// On Stream companion
def supervise[F[_]: Concurrent, A](fa: F[A]): Stream[F, Fiber[F, A]] =
  Stream.bracket(fa.start)(_.cancel)
```

**Comment by SystemFw** [comment] 2018-08-25 14:05
yeah that sounds like a good start. One problem I've had while thinking about `spawn` is how to decide the lifetime of the spawn-er: I basically wanted something that wouldn't terminate the spawned (unlike concurrently), but I realised that the only way to do that is `Stream.never`, or leaking `cancel` like the initial problem does.

However your latest `supervise` sounds better, perhaps it is enough :)

**Comment by mpilquist** [comment] 2018-08-25 14:32
Narrowed the cancelation bug down to `parJoin` - here's a small reproduction:

```scala
  "cancelation of compiled streams" - {
    // PASSES
    "constant" in testCancelation(Stream.constant(1))

    // PASSES
    "bracketed stream" in testCancelation(Stream.bracket(IO.unit)(_ => IO.unit).flatMap(_ => Stream.constant(1)))

    // PASSES
    "concurrently" in testCancelation {
      val s = Stream.constant(1).covary[IO]
      s.concurrently(s)
    }

    // HANGS
    "parJoin" in testCancelation {
      val s = Stream.constant(1).covary[IO]
      Stream(s, s).parJoin(2)
    }
```

`parJoin` runs the outer stream via `F2.start` and registers the fiber in stream scope, then in finalization, stops all the streams and waits for their shutdown. Here's the interesting thing -- the finalizer isn't run before the hang, which explains why the inner streams continue to run. Not sure what's causing the finalizer not to get run -- I'm guessing there's some other finalizer that was registered after that's hung.

**Comment by mpilquist** [comment] 2018-08-25 15:08
Tests started passing reliably when my laptop battery hit 4% and started failing reliably again when I plugged in a power cord. Points to a race condition.

**Comment by mpilquist** [comment] 2018-08-25 15:52
@pchlupacek I pushed the test cases to a branch. It appears that both `concurrently` and `merge` work fine but `parJoin` has a race condition. It appears related to finalization. Besides the battery example I mentioned above, I was also able to get it to pass by adding a bunch of printlns throughout scope closure code.

https://github.com/functional-streams-for-scala/fs2/commit/667037464cf1f35ce818316344c4bbc9c3f1341c

**Comment by mpilquist** [comment] 2018-08-25 16:47
Fixed in #1239 - bug was due to `Queue` returning `F.never` in case of cancelation.

**Closed** 2018-08-25 18:15 UTC

**Comment by pchlupacek** [comment] 2018-08-26 11:39
@mpilquist excellent catch. Was quite wondering we did not get Green before merge, but is cool that we have it in. 
  
Also `supervise` seems nice.

**Comment by mpilquist** [comment] 2018-08-26 12:30
The failure on the first commit was the Scala.js build, which failed because the tests don’t ever yield CPU time to other tasks, resulting in no cancelation getting requested.

**Comment by pchlupacek** [comment] 2018-08-26 16:33
yeah, somehow I am failing to read failures in travis PR builds. Thanks for clarification.
