### ISSUE TITLE
nondeterminism of error propagation

### ISSUE THREAD

**Issue by alissapajer** [functional-streams-for-scala/fs2#381] opened 2015-05-04 11:07 UTC
Here's a failing (nondeterministic) scalacheck test that can be dropped into `ProcessSpec`:

```scala
  // already defined in `ProcessSpec`
  case object FailWhale extends RuntimeException("the system... is down")

  property("propagate thrown exception") = {
    val killSignal = async.signalOf(false)
    val completed = Process eval_ killSignal.set(true)

    val exceptionT = Task delay { throw FailWhale }
    val exception = Process eval exceptionT onComplete completed

    val result = (killSignal.discrete wye exception)(wye.interrupt)

    forAll { _: Unit =>
      result.run.attemptRun == -\/(FailWhale)
    }
  }
```
The test's nondeterminism can be seen in the output with results like the following, where the test passes 14 times before failing. 
```
[info] ! Process.propagate thrown exception: Falsified after 14 passed tests.
```
What this means in the real world: It is possible to construct a `Process` that nondeterministically errors or doesn't error when run.

I claim that this code should always error with `FailWhale`. But sometimes, the process runs to a successful output of `\/-(())` instead of the expected `-\/(FailWhale)`.

I believe there is a race condition between which "kill condition" ultimately wins, the two conditions being the `wye.interrupt` interrupting successfully or the `FailWhale` exception (the original cause of the halt) propagating out.

Here is a slightly more complex test in which there is an extra a layer of indirection through a `wye.merge`. This example always (from what I've seen) drops the `FailWhale` exception, returning `\/-(())`.

```scala
property("propagate thrown exception through merge (pt 1)") = {
    val killSignal = async.signalOf(false)
    val completed = Process eval_ killSignal.set(true)

    val stuff = Process.constant(12).toSource

    val exceptionT = Task delay { throw FailWhale }
    val exception = Process eval_ exceptionT

    val merged = (stuff onComplete completed) merge exception
    // test produces same result with this version of `merged`
    // val merged = stuff merge (exception onComplete completed)

    val result = (killSignal.discrete wye merged)(wye.interrupt)

    forAll { _: Unit =>
      result.run.attemptRun == -\/(FailWhale)
    }
  }
```
This example raises a question about the priority of process termination causes. There is no doubt that `merged` halts because of the thrown exception `FailWhale`. With that logic, `result` should also halt due to the same exception, and the process should error when run. But since `killSignal` is subsequently set, which triggers the `wye.interrupt`, the original cause is lost, which is incorrect.

Edit: pushed wip/exception-specs which contains these tests.

**Comment by alissapajer** [comment] 2015-05-04 11:22
Quick note on how this affected me: I was checking specs2 properties inside a `Process` and observed that the `Exception`s that specs2 creates (e.g. `org.specs2.matcher.MatchFailureException`) were not always propagating out, meaning that my test would appear to pass when actually it was failing.

**Comment by djspiewak** [comment] 2015-05-04 17:34
Just to update this issue with the results of some discussion offline…

This is caused by the behavior of `stepAsync` in returning *immediately* upon interrupt.  In other words, it's not a bug per se but rather a function of our asynchronous interrupt semantics.  I'm not claiming that makes the behavior any more desirable, but fixing it isn't a simple matter of tracking down a bug.

One thing we can do is something like this:

```scala
def evalCatch[F[_], A](fa: F[A]): (Process[F, A], Signal[Throwable]) = {
  val s = async.signalUnset[Throwable]
  val p = awaitOr(fa)({
    case c @ Error(t) =>
      s.set(t) runAsync { _ => () }
      Process.halt causedBy c
    case c => Process.halt causedBy c
  })(emit)

  (p, s)
}
```

If an exception is produced by the effect, it *will* deterministically appear in the signal.  Otherwise the signal will never complete.  We could do `Signal[Option[Throwable]]` if that is deemed more useful.

**Comment by pchiusano** [comment] 2016-02-11 16:42
This is now fixed in the new design. The interrupt semantics are a lot more clear now. When shutting down a `Pull`, there may be outstanding `awaitAsync` steps still running. Here is what we do to cleanly shut down each of them:

* If a step is in the middle of running an effect that acquires a resource, we wait until that effect completes before returning, then free that resource.
* If a step is doing anything else, we close the 'resource acquisition gate' then return immediately. The step will continue running in the background until it reaches the next cycle of the Stream interpreter (at which point it will be halted) or until it is garbage collected, if it does not occupy a thread. 

See #526.

**Closed by pchiusano** 2016-02-11 16:42 UTC
