### ISSUE TITLE
Moving data through queue leaks memory

### ISSUE THREAD

**Issue by avakhrenev** [functional-streams-for-scala/fs2#1026] opened 2017-12-19 13:55 UTC
The following program
```scala
Stream.eval(async.boundedQueue[IO, Either[Throwable, Option[Int]]](10)).flatMap { queue =>
  queue.dequeueAvailable.rethrow.unNoneTerminate
    .concurrently(
      Stream.constant(1, 128).covary[IO].noneTerminate.attempt.evalMap(queue.enqueue1(_)))
    .evalMap(_ => IO.unit)
}
```
leaks memory. Here is what Eclipse Momory Analyzer shows:

![image](https://user-images.githubusercontent.com/1060224/34160146-cdc2789c-e4dc-11e7-8fb2-24e0ec1f980c.png)

![image](https://user-images.githubusercontent.com/1060224/34160186-fb5908f2-e4dc-11e7-89f4-9754828a15eb.png)

![image](https://user-images.githubusercontent.com/1060224/34160234-2b55fd76-e4dd-11e7-9aea-cfe92a8f7e4b.png)

fs2 version is 0.10.0-M9

**Comment by avakhrenev** [comment] 2017-12-19 14:37
I'm running it from sbt via `runMain` with this setting enabled:
`connectInput in run := true`
This allows me to interrupt the program by hitting `Enter`

<details><summary>Here is a full program for copy-pasting</summary><p>

```scala
package com.example

import cats.effect.IO
import fs2._
import fs2.StreamApp.ExitCode
import cats.syntax.apply._

object MemorySanityCheck extends StreamApp[IO] {

  override final def stream(args: List[String], requestShutdown: IO[Unit]): Stream[IO, ExitCode] =
    (io
      .readInputStream[IO](IO(System.in), 32, false)
      .takeWhile(_ != '\n') //read System.in to the end
      .drain
      .onFinalize(IO(println("Exiting...")) *> requestShutdown) mergeHaltBoth app(
      args,
      requestShutdown).evalMap(_ => IO.unit).drain).handleErrorWith(err =>
      Stream.eval(IO {
        err.printStackTrace(System.out)
        ExitCode.Error
      }))

  def app(args: List[String], requestShutdown: IO[Unit]): Stream[IO, Any] =
    Stream.eval(async.boundedQueue[IO, Either[Throwable, Option[Int]]](10)).flatMap { queue =>
      queue.dequeueAvailable.rethrow.unNoneTerminate
        .concurrently(
          Stream.constant(1, 128).covary[IO].noneTerminate.attempt.evalMap(queue.enqueue1(_)))
        .evalMap(_ => IO.unit)
    }
}
```
</p></details>

**Comment by avakhrenev** [comment] 2017-12-19 15:47
Promise, created at [this line](https://github.com/functional-streams-for-scala/fs2/blob/52f1b57b097be845996cd2d2331e3b8a01f146ba/core/shared/src/main/scala/fs2/Stream.scala#L2504) gets filled with unset callbacks

**Comment by mpilquist** [comment] 2017-12-19 16:01
@avakhrenev I'm surprised it's the promise in `unconsAsync` and not one in `Queue`

**Comment by avakhrenev** [comment] 2017-12-19 16:08
That's what I've seen after instrumenting `Promise` creation with [sourcecode](https://github.com/lihaoyi/sourcecode) and adding `printlns` when `waiting` map reaches 1000 elements. It may be not a root cause.

**Comment by mpilquist** [comment] 2017-12-19 16:23
@SystemFw Totally guessing here, but this could occur if the cancellation action in `AsyncPull#race` wasn't unregistering from the promise's state. Quick spot check appears fine though.

**Comment by SystemFw** [comment] 2017-12-19 16:26
`AsyncPull#race` is definitely the bit of the concurrency PR I'm less confident about. However, I'm still unsure exactly how and where `unconsAsync` enters the picture in the queue example...

**Comment by avakhrenev** [comment] 2017-12-19 16:28
It may be triggered by surrounding code, which reads from input stream simultaneously with running data through queue using `mergeHaltBoth` combinator.

**Comment by SystemFw** [comment] 2017-12-19 16:29
ah, `mergeHaltBoth`! 
I didn't see that, but that's far more likely.

**Comment by mpilquist** [comment] 2017-12-19 16:38
@avakhrenev I just ran the sample code without the surrounding stream interruption stuff and I haven't been able to reproduce a memory leak. I suspect the real leak is in merge when one of the sides doesn't make progress.

**Comment by SystemFw** [comment] 2017-12-19 16:39
a leak on `merge` makes a lot more sense to me, since that's where `AsyncPull.race` is involved.
Not sure if it's a problem with `race`, or just another case of `a.drain merge b` not being good enough .

**Comment by avakhrenev** [comment] 2017-12-19 16:43
Interesting, I've just removed reading from input stream with `mergeHaltBoth` and got the same result: instances of `Promise`, allocated in `ToPull#unconsAsync` continue to grow. Here is the full code for reference:
```scala
package com.example

import cats.effect.IO
import fs2._
import fs2.StreamApp.ExitCode

object MemorySanityCheck extends StreamApp[IO] {
  import scala.concurrent.ExecutionContext.Implicits._

  override final def stream(args: List[String], requestShutdown: IO[Unit]): Stream[IO, ExitCode] = {
    Stream.eval(async.boundedQueue[IO, Either[Throwable, Option[Int]]](10)).flatMap { queue =>
      queue.dequeueAvailable.rethrow.unNoneTerminate
        .concurrently(
          Stream.constant(1, 128).covary[IO].noneTerminate.attempt.evalMap(queue.enqueue1(_)))
        .evalMap(_ => IO.unit)
    }.drain ++ Stream(ExitCode.Error)
  }
}
```

**Comment by mpilquist** [comment] 2017-12-19 16:44
@avakhrenev Can you try without `StreamApp`? Here's what I tried:

```scala
object QueueTest extends App {
  import ExecutionContext.Implicits.global
  Stream.eval(async.boundedQueue[IO, Either[Throwable, Option[Int]]](10)).flatMap { queue =>
    queue.dequeueAvailable.rethrow.unNoneTerminate.concurrently(
      Stream.constant(1, 128).covary[IO].noneTerminate.attempt.evalMap(queue.enqueue1(_))
    ).evalMap(_ => IO.unit)
  }.run.unsafeRunSync()
}
```

**Comment by mpilquist** [comment] 2017-12-19 16:45
This program definitely leaks:

```scala
object HungMerge extends App {
  import ExecutionContext.Implicits.global
  val hung = Stream.eval(IO.async[Int](_ => ()))
  val progress = Stream.constant(1, 128).covary[IO]
  (hung merge progress).run.unsafeRunSync()
}
```

**Comment by mpilquist** [comment] 2017-12-19 16:48
Note `StreamApp` uses an `interruptWhen` on the result of `def stream`, resulting in a call to `merge`.

**Comment by avakhrenev** [comment] 2017-12-19 16:50
Hm, your program leaks also, or maybe I'm misinterpreting results. I've added println at `Promise.scala:96`:
```scala
case State.Unset(waiting) =>
  val wu = waiting.updated(id, cb)
  State.Unset(wu) -> F.delay[Unit](
    if(wu.size > 100)
      println(s"Waiters size is: ${wu.size}")
    else ())
```

**Comment by SystemFw** [comment] 2017-12-19 16:59
Wait,  does `QueueTest` leak or not?

In any case,  `HungMerge` does, so would you say this is a bug on `AsyncPull.race` (which I should probably start working on)? No problem with non-hung `merge`, I'm assuming

**Comment by mpilquist** [comment] 2017-12-19 17:00
@avakhrenev Yeah, I see a slow leak in `QueueTest`, though it is much, much slower than the leak in `merge` -- about ~200MB over 5 minutes on my machine.

@SystemFw I'll test non-hung merge now.

**Comment by mpilquist** [comment] 2017-12-19 17:05
Merging 2 progressing streams does not leak:

```scala
object ProgressMerge extends App {
  import ExecutionContext.Implicits.global
  val progress = Stream.constant(1, 128).covary[IO]
  (progress merge progress).run.unsafeRunSync()
}
```

**Comment by SystemFw** [comment] 2017-12-19 17:23
@mpilquist Probably found the cause, `cancellableGet` in Promise. I'll start working on a fix/precise diagnosis and we can then see if the leaks are also fixed.

**Comment by mpilquist** [comment] 2017-12-19 21:29
Fixed by #1027

**Closed by mpilquist** 2017-12-19 21:29 UTC

**Comment by SystemFw** [comment] 2017-12-19 21:34
@avakhrenev Thanks a lot for spotting this, turns out it was a pretty serious problem.
Matter of fact, I'm surprised it "only" resulted in a memory leak and didn't break any tests.
Michael fixed it, in any case :)

**Comment by avakhrenev** [comment] 2017-12-19 21:49
@mpilquist @SystemFw Thank you for your great work!
