### ISSUE TITLE
Memory leak in Stream#parJoin

### ISSUE THREAD

**Issue by danielkarch** [functional-streams-for-scala/fs2#1316] opened 2018-11-09 12:37 UTC
Hello everyone,

I observed a memory leak in my application and found `parJoin` to be the cause. 
When I run this piece of code, the heap usage keeps growing slowly until it crashes with `java.lang.OutOfMemoryError: GC overhead limit exceeded`:
```scala
Stream.iterate(1)(_+1)
      .map(i => Stream.emit(IO(i)).covary[IO]).parJoin(1)
      .compile.drain
      .unsafeRunSync()
```
The heap usage over time:
![leak](https://user-images.githubusercontent.com/6737030/48262917-8b310000-e424-11e8-80ff-716843a31b1b.png)

And a heap dump:
![leak2](https://user-images.githubusercontent.com/6737030/48262925-9552fe80-e424-11e8-8b9c-0e6a9ecf17df.png)

**Comment by danielkarch** [comment] 2018-11-10 14:51
It does not appear to leak in version 0.10.6 using `join` instead of `parJoin`, which is not available in that version (or memory grows so slowly that I cannot tell after > 20 minutes, whereas the above picture shows memory growth after <5 minutes).

**Comment by Daenyth** [comment] 2018-11-11 13:14
Thanks for checking that.

**Comment by pchlupacek** [comment] 2018-11-11 13:51
@danielkarch can you please clarify fs2 version you seing this? I just run on 1.0 SNAPSHOT and I cannot reproduce the behaviour. 
<img width="1352" alt="screenshot 2018-11-11 at 14 50 15" src="https://user-images.githubusercontent.com/678560/48313765-455d6e80-e5c1-11e8-9726-6f3369836d8c.png">

**Comment by danielkarch** [comment] 2018-11-12 08:44
I tried on 1.0.0, and just on 1.0.0-SNAPSHOT, where I get the same behaviour. It is more apparent when running with a really small heap (I just ran it with 96MB).

**Comment by pchlupacek** [comment] 2018-11-12 08:45
@danielkarch could you confirm that the code is exactly as you posted it ?

**Comment by danielkarch** [comment] 2018-11-12 09:07
full code:
```scala
import cats.effect.{ExitCode, IO, IOApp}
import fs2.Stream
import cats.syntax.functor._

object Application extends IOApp {

  override def run(args: List[String]): IO[ExitCode] =
    Stream.iterate(1)(_+1)
      .map(i => Stream.emit(IO(i)).covary[IO]).parJoin(1)
      .compile.drain as ExitCode.Success

}
```

**Comment by pchlupacek** [comment] 2018-11-12 16:18
@danielkarch still doesn't seem to be able to reproduce. This is from 2m run of the program. As you may see the full-gc always clears the old-gen to about 4.8/5 MB. 

<img width="1361" alt="screenshot 2018-11-12 at 17 16 12" src="https://user-images.githubusercontent.com/678560/48360205-00a80500-e69f-11e8-9108-408a80c1fc3a.png">

**Comment by pchlupacek** [comment] 2018-11-12 16:43
@danielkarch seems like the 1.0 snapshot we publish is not actually synced with series/1.0. 
I will try to run this on 1.0 proper and lets see if I can reproduce this

**Comment by pchlupacek** [comment] 2018-11-12 16:50
@danielkarch I can now confirm that on 1.0 proper this indeed leaks. 
<img width="730" alt="screenshot 2018-11-12 at 17 49 28" src="https://user-images.githubusercontent.com/678560/48362184-5d0d2380-e6a3-11e8-8525-d2a1c7839d4e.png">
Good news is that in master this is fixed, I will try to find out the culprit to make sure that there is good understanding of the issue.

**Comment by pchlupacek** [comment] 2018-11-12 16:57
Ok I have understanding what was wrong. The parJoin had interruptWhen for every inner stream, that was using the discrete stream from SignallingRef, and that leaked which was fixed in #1308. So if you could please confirm that series/1.0 head does not leak in your case that would be excellent. 

@mpilquist do we still publish snapshots for current series/1.0 head? I failed to find them on maven (
https://oss.sonatype.org/content/repositories/snapshots/co/fs2/fs2-core_2.12/)

**Comment by mpilquist** [comment] 2018-11-12 16:58
Yep, in Sonatype Snapshots repository. 

```scala
resolvers += "Sonatype Public" at "https://oss.sonatype.org/content/groups/public/"
```

**Comment by pchlupacek** [comment] 2018-11-12 16:59
so snapshots live now in releases repo?

**Comment by mpilquist** [comment] 2018-11-12 17:00
No, the `Sonatype Public` repo proxies their SNAPSHOTs repo. https://oss.sonatype.org/content/groups/public/co/fs2/fs2-core_2.12/

**Comment by pchlupacek** [comment] 2018-11-12 17:01
this seems to be still out of date : 
https://oss.sonatype.org/content/groups/public/co/fs2/fs2-core_2.11/1.0.0-SNAPSHOT/

**Comment by mpilquist** [comment] 2018-11-12 17:04
Hmm, you are right. This line is short circuiting for some reason -- never running `sbt +publish`:

```
test $PUBLISH == "true" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "series/1.0" && sbt +publish
```

**Comment by pchlupacek** [comment] 2018-11-12 17:05
ok thanks for clarification :-)

**Comment by mpilquist** [comment] 2018-11-12 17:09
Correction, that line is fine, I was just looking at a PR build. Turns out publish is failing due to a GPG issue: https://travis-ci.org/functional-streams-for-scala/fs2/jobs/453982079#L4459

**Comment by mpilquist** [comment] 2018-11-12 17:44
SNAPSHOT publishing is fixed now. Make sure you depend on 1.0.1-SNAPSHOT.

**Comment by pchlupacek** [comment] 2018-11-12 18:15
@mpilquist thanks a lot. @danielkarch could you please try with 1.0.1-SNAPSHOT dependency?

**Comment by danielkarch** [comment] 2018-11-13 07:10
Looks good now, thank you!

**Comment by pchlupacek** [comment] 2018-11-13 09:41
@danielkarch excellent news. Closing this for now.

**Closed by pchlupacek** 2018-11-13 09:41 UTC

**Comment by Daenyth** [comment] 2018-11-13 11:41
Is there any word on when the snapshot is releasing?

**Comment by SystemFw** [comment] 2018-11-13 11:42
@Daenyth do you mean when we are going to have a proper point release? 
There are more issues here, plus we need a cats-effect release (there are a couple issues there).
I'm stretched very thin but trying to keep on top of it all :)

**Comment by Daenyth** [comment] 2018-11-13 12:45
Thanks for all the great work! It's very appreciated.
