### ISSUE TITLE
parJoin on error stream ++ Stream.never doesn't terminate

### ISSUE THREAD

**Issue by Daenyth** [functional-streams-for-scala/fs2#1491] opened 2019-06-06 15:35 UTC
This stream doesn't terminate:
```scala
Stream.emit(
 Stream.raiseError[IO](new IllegalStateException("kaboom"))
).parJoinUnbounded ++ Stream.never[IO]
```

Full repro: https://scastie.scala-lang.org/5FqDk4E7T2i1NrMm81lVBg

**Comment by SystemFw** [comment] 2019-06-06 15:55
```scala
  def hello = Stream.eval_(IO(println("hello")))
  def fail = Stream.raiseError[IO](new Exception("boom"))

  def a = Stream.emit(fail).parJoinUnbounded ++ hello
  // hello
  // java.lang.Exception: boom

  def b = Stream.emit(fail).covary[IO].flatten ++ hello
  // java.lang.Exception: boom

  def c = Stream(fail).compile.drain >> IO(println("hello"))
  // hello

  def d = Stream.emit(fail).parJoinUnbounded.handleErrorWith(_  => hello)
  // hello

  def e = Stream.emit(fail).parJoinUnbounded.onError{case _ => hello} ++ hello
  // hello
  // hello

  def f = fail ++ hello
  // java.lang.Exception: boom

  def g = Stream.emit(fail).parJoinUnbounded >> hello
  // java.lang.Exception: boom
```

in the interaction between a `parJoin`ed Stream and `++`, the error doesn't get propagated.
`e` is especially weird.

**Comment by pchlupacek** [comment] 2019-06-06 16:12
hm this seems to be related to some new updates re: the scopes and ++ interaction imho. I am feeling that `e` seems to be correct. Otoh `a` is completely wrong. Can you try manually ad scope between parJoinUnbounded and ++ ? 

Any chance we could track this back to 1.0.x releases ?  I think we may find when this got introduced, I am feeling this was correct in final.

**Comment by SystemFw** [comment] 2019-06-06 16:14
`onError` is `handleErrorWith` plus rethrowing. 
So it should print the first `Hello`, then rethrow and `++` should short circuit, so `e` is weird.

I have to go but I'll try looking into this later tonight.

**Comment by pchlupacek** [comment] 2019-06-06 16:18
@SystemFw ah sorry, still on RC, so missing some of the suff in final :-) Then right `e` is weird too. Which cats version is used?

**Comment by pchlupacek** [comment] 2019-06-06 16:21
@SystemFw are we still waiting for finalizers to terminate before moving to ++ ? Or are the finalizers now running w/o actually waiting for them to finalize?

**Comment by mpilquist** [comment] 2019-06-06 16:50
Add `.scope` before `++` to see if scope changes are the issue -- the original example indeed behaves as expected with an explicit scope before append.

**Comment by AdamChlupacek** [comment] 2019-06-06 16:52
I can confirm that adding `.scope` to `a` before the `++` fixes the issue.

**Comment by pchlupacek** [comment] 2019-06-06 16:53
@mpilquist this seems a bit magic to me whats your theory here ?

**Comment by mpilquist** [comment] 2019-06-06 16:57
@pchlupacek No specific theory, just something I noticed when we made the scope changes -- there were some tests that were relying on finalizers getting run by the Release node that now rely on them getting run by scope closure. Take a look at #1417, specifically this change: https://github.com/functional-streams-for-scala/fs2/pull/1417/files#diff-7df69c6557bf4cdbc811cbd90941cdcbR1716

**Comment by AdamChlupacek** [comment] 2019-06-06 16:59
@mpilquist As far as I see, we currently only release resources when the scope is finished. `parJoin` error propagation is done via `F.raiseError` in release of bracket, as such we only get the error propagated when the scope is released. So perhaps we really do need the explicit scope there?

**Comment by mpilquist** [comment] 2019-06-06 16:59
@AdamChlupacek Yep, I think that's exactly right

**Comment by pchlupacek** [comment] 2019-06-06 17:05
ok cool.

**Comment by AdamChlupacek** [comment] 2019-06-06 17:14
Introducing the scope does fix most of the behaviour, I am still struggling with `onError` scenario, where it behaves as if the exception did not get rethrown. When I use `handleErrorWith` and manually rethrow it, all is working as expected. Maybe something up with `onError`? not sure. 

Anyhow will make a PR with tests for the scope.

**Comment by mpilquist** [comment] 2019-06-06 17:23
This is kind of interesting:

```scala
@ val S = MonadError[Stream[IO, ?], Throwable]
S: MonadError[Stream[IO, β$0$], Throwable] = fs2.Stream$$anon$1@5597ca3

@ S.map2(Stream.eval_(IO(println("inner"))), Stream.raiseError[IO](new Throwable))((_, b) => b) ++ Stream.eval(IO("end"))
res2: Stream[IO[x], String] = Stream(..)

@ res2.compile.toList.unsafeRunSync
inner
res3: List[String] = List("end")
```

**Comment by AdamChlupacek** [comment] 2019-06-06 17:24
Yeah `onError` does not work as it is implemented via `map2` and since we are in streams, and `hello` does not emit any values, the `map2` does not get to rethrow as it is "waiting" for the first `F` to emit value. Quite dangerous thing to use with streams imho.

**Comment by AdamChlupacek** [comment] 2019-06-06 17:25
Its all because of the `eval_`

**Comment by mpilquist** [comment] 2019-06-06 17:28
Yeah, seems like we want some other method that has same signature as `onError` but does what you'd expect. Don't want to use the same name as we'd likely break `ApplicativeError` laws.

**Closed** 2019-06-06 18:13 UTC

**Comment by SystemFw** [comment] 2019-06-06 19:08
> Don't want to use the same name as we'd likely break ApplicativeError laws.

Is this a consistent criterion? We already use the same name for things like `foldMap`, and there's an argument for naming this new op `onError` to make it harder to get the wrong one (it will shadow the one from cats)

**Comment by SystemFw** [comment] 2019-06-06 19:08
Also, nothing nicer than coming back to this and see it's already fixed, thanks guys :)

**Comment by mpilquist** [comment] 2019-06-06 19:13
@SystemFw Yeah, I suppose it's not so bad if we define `onError` as a `Stream` method. The `ApplicativeError#onError` would NOT get overridden though, and hence, no laws are violated.
