### ISSUE TITLE
Add primitive support for interruption

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#916] opened 2017-08-07 18:26 UTC
In the PR review of #914, @pchlupacek pointed out that `interruptWhen` in 0.9 and 0.10 cannot interrupt all stream types. The issue is caused by the fact that `interruptWhen` is implemented in terms of `merge`, and downstream from the application of `interruptWhen`, a caller can `flatMap` and turn a single element in to an infinite stream, causing the merger to never be re-evaluated.

```scala
// 0.9.7
Stream.eval(async.signalOf[Task,Boolean](false)).flatMap(s => Stream.eval_(Task.start(s.set(true).schedule(1.second))) ++ Stream.emit(s).interruptWhen(s)).flatMap(s => s.discrete).runLog.unsafeRunAsync(println)
```

Instead of implementing `interruptWhen` in terms of `merge`, we could add primitive interruption support to `runFold`. There are probably a few different ways to do this.

@pchiusano What do you think? Any advice on implementing this?

**Comment by pchlupacek** [comment] 2017-08-08 15:24
Just as remark note, this not only causes program to not interrupt but also swallows the exceptions in the stream graph causing the whole program to enter into unstable state.

**Comment by mpilquist** [comment] 2017-08-17 21:55
@pchlupacek I took a shot at implementing the start of this but ran in to some pretty big problems.

I added a `interrupted: AtomicBoolean` parameter to `runFold_` and checked on each invocation of `go`. I also added a new primitive to the algebra: `final case class GetInterrupt[F[_],O]() extends Algebra[F,O,F[Unit]]`

As an initial take on `interruptWhen`, I tried:
```scala
    def interruptWhen(haltWhenTrue: Stream[F,Boolean])(implicit F: Effect[F], ec: ExecutionContext): Stream[F,O] =
      fromFreeC(Algebra.interrupt[F,O].flatMap { interrupt =>
        self.concurrently(haltWhenTrue.takeWhile(!_, true).filter(identity).evalMap(_ => interrupt)).get
      })
```

This definition is problematic though because it uses `concurrently` and the implementation of `concurrently` uses `interruptWhen`. So then I tried a simple test:

```scala
    def interruptWhen(haltWhenTrue: Stream[F,Boolean])(implicit F: Effect[F], ec: ExecutionContext): Stream[F,O] =
      fromFreeC(Algebra.interrupt[F,O].flatMap { interrupt =>
        // TODO handle errors in monitor, terminate monitor at end of self
        val monitor = haltWhenTrue.takeWhile(!_, true).filter(identity).evalMap(_ => interrupt)
        Stream.eval_(async.fork(monitor.run)).append(self).get
      })
```

This works in many use cases but not all -- notably, if the main stream is hung on an eval, it cannot be cancelled. The ability to cancel a hung stream comes for free with the old implementation because we pull from either the source stream or the interruption stream. But with this implementation, the main stream doesn't get a chance to interrupt until next loop through `go`  in `runFold_` and it won't get there until the running eval finishes.

Not sure where to go from here honestly. The semantics of the existing `interruptWhen` are certainly better than the semantics of this most recent attempt.

Do you have any other ideas?

BTW, I pushed this work to the wip/interrupt-fork branch.

**Comment by pchlupacek** [comment] 2017-08-18 03:36
@mpilquist thanks. I will look onto that tmrw.  By any chance can you share example of the stream that hungs? Is that something what contains something like Stream.eval(q.dequeue1) or similar ?

**Comment by mpilquist** [comment] 2017-08-18 13:00
@pchlupacek The `interrupt(1)` and `interrupt(3)` tests in `Pipe2Spec` demonstrate the problem.

**Comment by pchlupacek** [comment] 2017-08-18 14:50
@mpilquist ok thanks

**Comment by pchiusano** [comment] 2017-08-22 19:07
So, I kind of think that `interruptWhen` semantics (based on the elegant, simple merge-based version that anyone can understand) are fine and we shouldn't try to engineer something more complicated. It's okay if the 0.9 and 0.10 version of `interruptWhen` aren't appropriate for all use cases. Maybe there is another combinator that could be written that's useful... but I think this needs more design work (maybe post 0.10 release). @pchlupacek let us know what you come up with here.

One thing is I really want to avoid adding new primitives to the FS2 algebra, especially not for particular special uses that most users don't encounter.

**Comment by pchlupacek** [comment] 2017-11-26 17:48
I am in middle of the design of new interruptWhen variant, and essentially came up to the design issue that we sort of shall agree on: 

Given the following program: 
```scala 

trait Resource {
   def useResource: Stream[F, A]

}

val sResource: Stream[F, Resource] = {
   
   val runResourceEffects: Stream[F, Unit]
   
   val resource = new Resource {
       def useResource: Stream[F, A] = .... // depends on runResource to be run, and not failing 
   }
    Stream.emit(resource).concurrently(runResourceEffects)
   } 
}

// program
sResource.flatMap {  r =>
  r.useResource
}

```

If we have `runResourceEffects` failing or stops to run, it is obvious that `r.useResource` shall fail too. In current (0.9, 0.10) it is not the case. 

Now the question is do we want this to be done automatically (i.e. behind the scenes) or do we want user to be responsible for that somehow ?

**Comment by mpilquist** [comment] 2017-11-26 18:24
@pchlupacek Yes, I think that should be done automatically.

**Comment by pchlupacek** [comment] 2017-11-26 18:39
@mpilquist I have this implemented, however the trouble with this approach is that this program will also get interrupted (whole tree) and I am not sure if that is intuitive engough: 

```scala

Stream.constant(true) merge (Stream.constant(false).interruptWhen(...)) 

```
In this case I would expect the Left stream to continue when the Right stream terminates (on the interruption) .  And I am not sure why flatMapped variant shall be interrupted but this one should not be. Or at least I don't see clear algorithm when the interrupt shall stop evaluation of whole stream and when shall not. 
 
Perhaps we can somehow bring in scopes in play ?

**Comment by pchlupacek** [comment] 2017-11-27 05:52
@mpilquist, @SystemFw  I would suggest to define something called `interruption boundary` this is essentially the point in the stream evaluation, up to when interruption has an effect. This is only in case interruption terminated the stream without error. 

this would be : 
 - `merge`, `either` : interruption of either stream (l, R) won't cause the whole stream to terminate, only that particular leg

- `append`, `++`, `handleErrorWith` : interruption of stream before combinator won't terminate stream after combinator

My idea for implementing these boundaries will usage of the scopes: 
 
While current `merge` and `either` are creating `nested` children scopes, I would create new root scope, and current root scopes of left and right streams demote to be children scopes of  newly created root scope.  As an implementation note, perhaps we have to return to Stream.pull2, that performs this magic. 

 Append ('++') will have to be more complicated as it is now, unfortunately, because we will need always with append to create new scope that will be sibling of s1. so for examples s1++ s2 will create scopes for s1 and s2, both of them sharing same parent. 

Analogically `handleErrorWith` will create two scopes like `++` but will handle errors from earlier scope, if any.

I think that should be enough intuitive to not bring any unexpected behaviour to user and least possible confusion from the current state of the stream programs. 

What do you think ?

**Comment by mpilquist** [comment] 2017-11-27 12:36
@pchlupacek I'm hesitant to make `++` more complex as it will likely severely hurt performance for streams that don't use interruption. Note that `++` doesn't currently introduce a new scope. In #930 we tried adding a scope but found the performance tradeoff to be really, really bad. Hence in #939 we added the ability to manually specify scope boundaries.

**Comment by pchlupacek** [comment] 2017-11-27 14:10
@mpilquist I see, and I am not happy with that either. The problem I see here is that you cannot effectively use scopes for interruption now, hence the ++ does not introduce new scope, and as such any concatenated stream will be interrupted as whole now, unless scope is introduced at its boundaries.

To me this really comes down with the example demonstrated above. If we somehow want to terminate from the `upstream` the whole `downstream` we have to somehow tell to interpreter, where it shall resume (if any) normal operation. 

I will think on how that could be done. I am sure there is a way, its just not that obvious to me now 

On another topic I am thinking of, and  I am quite sure you have already explored that path, but just to not overlook this. How about defining the Stream's `get` to return some result from previous evaluation (lets say Boolean for simplicity now) to signal whether stream was interrupted and shall/shall not continue its evaluation? Then attempt will be as it is, and where we need to somehow decide the interruption we can do it.  Is just very rough /and not well though/ idea yet...

**Comment by pchlupacek** [comment] 2017-11-28 18:54
@mpilquist I investigated more how to resolve this and still not happy with any solution. In fact I still don't have even `bad` solution yet. 
However I am now quite sure that we must unfortunatelly resolve this, as I have minimalistic test from program that needs to pass, and does not: 
```scala

"when background stream fails, overall stream fails (2)" in forAll { (s: PureStream[Int], f: Failure) =>
      val prg = Scheduler[IO](1).flatMap(scheduler => (scheduler.sleep_[IO](25.millis) ++ s.get.flatMap(idx => Stream.constant(idx))).concurrently(f.get))
      val throws = f.get.drain.run.attempt.unsafeRunSync.isLeft
      if (throws) an[Err.type] should be thrownBy runLog(prg)
      else runLog(prg)
    }

```
As you may see there is no magic in it, it is pretty standard program, yet in 0.10/0.9 this never terminates (fails). Obviously instead of the Stream.constant you may have any asynchronous callback, that will never terminate ever :-)

**Comment by mpilquist** [comment] 2017-11-28 18:58
@pchlupacek Have you recently considered any ideas like the one I tried back on https://github.com/functional-streams-for-scala/fs2/issues/916#issuecomment-323205221

**Comment by pchlupacek** [comment] 2017-11-28 19:09
@mpilquist yeah, sort of. Hence we have scope now, we can implement these even w/o the need of new algebra. In fact I have working solution that interrupts stream in every situation, with proper failures etc.. The problem is that I don't know how to recover in case of ++ (i.e interruptible ++ next) or failures that will be handled with onError.... there you want to recover interrupted/failed stream and I simply don't know yet how to do that, i.e. 

```scala 

val s1 = someStream.concurrently(runnerStream)

s1 ++ s2 .// s2 shall continue when s1 interrupts
s1 onError { _ => s2 } // s2 shall continue when runnerStream fails
s1.flatMap { o => mkS3(o) ++ s2 } // s3, s2 shall be interrupted hence they in flatMap 

// and so on... 

```

**Comment by pchlupacek** [comment] 2017-11-29 13:44
@mpilquist I have thought about this agan, and: 
1. We need to correctly propagate failure. That is ok for now and work perfectly unless there is no Effect combinator (i.e. concurrently, merge) that eventually may produce failures before stream is ready to consume more
2. interruption is kinda not completely necessary for whole stream, usually it is required only at certain scope. 

As a result I think (1) has to be fixed before 0.10 final. (2) is currently what we have, and if someone needs that to behave differently (1) could be used to achieve it. There may be perhaps a little bit optimisation in it and I have that done and will submit PR separate from resolution of (1)

So I am focusing now on (1). It turns out, that whenever you need asynchronously interrupt the stream is only if your `F` allows to construct `Effect` combinator, such as merge, join ... In these cases, I will need somehow to propagate that Effect instance to runFold. Any idea on how to do that? 

Thanks.

**Comment by mpilquist** [comment] 2017-11-29 13:45
We used to propagate the effect instance b/c it was captured in `UnconsAsync` -- take a look at the `runFoldScope` signature before your recent PR that changed that stuff. I'm really happy that's all gone though...

**Comment by pchlupacek** [comment] 2017-11-29 14:26
@mpilquist yeah, I know. Another option I was thinking is to require for `run` LiftIO instance?

**Comment by pchlupacek** [comment] 2017-11-29 14:28
ah nvm that doesn't make any sense

**Closed** 2018-01-03 17:52 UTC
Labels: design/refactoring
