### ISSUE TITLE
"Cannot open new scope on a closed scope" Exception when zipping two mapped streams

### ISSUE THREAD

**Issue by filosganga** [functional-streams-for-scala/fs2#941] opened 2017-10-04 12:39 UTC
This piece of code:

```scala
Stream(1,2,3).map(_ + 1).repeat.zip(Stream(4,5,6).map(_ + 1).repeat).take(48).toList
```

Raises:
```
Cannot open new scope on a closed scope
java.lang.IllegalStateException: Cannot open new scope on a closed scope
    at fs2.internal.Algebra$Scope.open(Algebra.scala:109)
    at fs2.internal.Algebra$.$anonfun$runFold_$8(Algebra.scala:267)
    at cats.effect.IO$.$anonfun$suspend$1(IO.scala:381)
    at cats.effect.internals.AndThen.processSuccess$1(AndThen.scala:48)
    at cats.effect.internals.AndThen.runLoop(AndThen.scala:65)
    at cats.effect.internals.AndThen.apply(AndThen.scala:34)
    at cats.effect.IO.unsafeStep(IO.scala:175)
    at cats.effect.IO.unsafeRunTimed(IO.scala:264)
    at cats.effect.IO.unsafeRunSync(IO.scala:199)
```

It works fine in all this cases:

If we remove one of the call to map:
```scala
Stream(1,2,3).repeat.zip(Stream(4,5,6).map(_ + 1).repeat).take(48).toList

Stream(1,2,3).map(_ + 1).repeat.zip(Stream(4,5,6).map(_ + 1).repeat).take(48).toList
```

If we `take` with a value smaller or equal to the original Stream leangth:
```scala
Stream(1,2,3).map(_ + 1).repeat.zip(Stream(4,5,6).map(_ + 1).repeat).take(3).toList
```

**Comment by SystemFw** [comment] 2017-10-04 13:24
Reported by another user as well. It might also be related to the case encountered in #939

**Comment by SystemFw** [comment] 2017-10-04 13:32
@filosganga What version are you on?

**Comment by filosganga** [comment] 2017-10-04 13:56
@SystemFw 0.10.0-M6

**Comment by mpilquist** [comment] 2017-10-06 21:21
Spent some time with this one today...

The calls to `.map(_ + 1)` are relevant because they introduce a scope around the finite streams. The calls to `.repeat` are red-herrings. Here's another reproduction:

```scala
Stream(1).pull.echo.stream.append(Stream(2).pull.echo.stream).zip(Stream(4).pull.echo.stream.append(Stream(5).pull.echo.stream)).toList
```

Here, I used `s.pull.echo.stream` to wrap `s` with its own scope. During interpretation, I pretty sure there's an interleaving of open & close scope calls (due to the left and right streams in the zip) such that a close scope restores the interpreter back to a scope that's already been closed.

I think we might be able to fix this by changing `Algebra.Scope` so that it tracks its parent scope. Then when closing a scope, if `scopeAfterClose` is itself already closed, we recursively walk up the parent tree until we encounter a non-closed scope.

**Comment by mpilquist** [comment] 2017-10-06 21:30
Eh, probably better to remove `scopeAfterClose` from `CloseScope` and just always recursively walk up the parent tree.

**Closed** 2017-10-11 02:35 UTC
Labels: bug
